# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Caleb Johann's Website"
weight = 1

[ja]
languageName = "Japanese"
languagedirection = "ltr"
title = "Caleb Johann'sウェッブ"
weight = 1
